### ISSUE TITLE
Can I complete my homework on the Win platform?

### ISSUE THREAD

**Issue by BILY5354** [remzi-arpacidusseau/ostep-homework#53]
- Now my code env on Win is
   - win 64
   - vs code 
   - MinGw
- I can run the simulator in chapter 4 on the Win platform without any problems
- But now the following error occurs in Chapter 5
![image](https://user-images.githubusercontent.com/46767838/212210483-c8de0888-2332-4484-ab2a-a9c4bbb4bcde.png)
- I found out after searching that this is not a Win library.What I need to do if I want to run on win (so I don't need to configure linux again)
- Also I would like to ask how to know when certain libraries are not available on win (like this ```#include <sys/wait.h>```). Thanks you.

**Comment by GusSand** [comment]
I would recommend instead of using MinGW in the windows platform to use WSL (Windows Subsystem for Linux). Once you do that, you would have all the tools to run anything and everything in one command shell. That’s what my students use for my operating Systems course. Here’s a link: https://learn.microsoft.com/en-us/windows/wsl/install 

Good luck!
G

**Comment by BILY5354** [comment]
Thanks.
